theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.9.2
  download_url: https://github.com/chrisant996/clink/releases/download/v1.9.2/clink.1.9.2.6aa2e0.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.9.2/clink.1.9.2.6aa2e0_setup.exe
