theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.9.14
  download_url: https://github.com/chrisant996/clink/releases/download/v1.9.14/clink.1.9.14.d5f9a7.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.9.14/clink.1.9.14.d5f9a7_setup.exe
