theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.9.6
  download_url: https://github.com/chrisant996/clink/releases/download/v1.9.6/clink.1.9.6.3ded5d.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.9.6/clink.1.9.6.3ded5d_setup.exe
