theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.9.5
  download_url: https://github.com/chrisant996/clink/releases/download/v1.9.5/clink.1.9.5.ee6b4f.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.9.5/clink.1.9.5.ee6b4f_setup.exe
