theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.9.7
  download_url: https://github.com/chrisant996/clink/releases/download/v1.9.7/clink.1.9.7.b33c45.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.9.7/clink.1.9.7.b33c45_setup.exe
