theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.9.11
  download_url: https://github.com/chrisant996/clink/releases/download/v1.9.11/clink.1.9.11.760de7.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.9.11/clink.1.9.11.760de7_setup.exe
