theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.9.8
  download_url: https://github.com/chrisant996/clink/releases/download/v1.9.8/clink.1.9.8.c53f59.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.9.8/clink.1.9.8.c53f59_setup.exe
