theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.9.9
  download_url: https://github.com/chrisant996/clink/releases/download/v1.9.9/clink.1.9.9.3fd236.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.9.9/clink.1.9.9.3fd236_setup.exe
