theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.5.10
  download_url: https://github.com/chrisant996/clink/releases/download/v1.5.10/clink.1.5.10.faf29d.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.5.10/clink.1.5.10.faf29d_setup.exe
