theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.8.8
  download_url: https://github.com/chrisant996/clink/releases/download/v1.8.8/clink.1.8.8.a63364.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.8.8/clink.1.8.8.a63364_setup.exe
