theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.9.0
  download_url: https://github.com/chrisant996/clink/releases/download/v1.9.0/clink.1.9.0.074e53.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.9.0/clink.1.9.0.074e53_setup.exe
