theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.9.4
  download_url: https://github.com/chrisant996/clink/releases/download/v1.9.4/clink.1.9.4.32ec3a.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.9.4/clink.1.9.4.32ec3a_setup.exe
